[bastion]
130.193.39.195

[webservers]
10.0.1.4
10.0.2.34

[webservers:vars]
ansible_user=user
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@130.193.39.195"'

[dbservers]
10.0.2.33

[dbservers:vars]
ansible_user=user
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@130.193.39.195"'

