#cloud-config
users:
  - name: dmitry
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKcJnCxtZGhVAoGCl/hZPKHJ+QF8fQCFnnhxygRfTZGB dmitry@dmitry-VirtualBox
